{
"openapi"
:
"3.0.1",
"info": {
"title"
:
"Demo API",
"description"
:
"This is a demo API documentation",
"version"
:
"v1"
},
"servers": [
{
"url"
:
"http://localhost:8080",
"description"
:
"Generated server url"
}
],
"paths": {
"/api/hello": {
"get": {
"tags": [
"hello-world-controller"
],
"operationId"
:
"helloWorld",
"responses": {
"200": {
"description"
:
"OK",
"content": {
"*/*": {
"schema": {
"type"
:
"string"
}
}
}
}
}
}
}
},
"components": {
}
}